name: unlearn
channels:
  - defaults
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - anaconda-anon-usage=0.7.2=py313hfc0e8ea_100
  - anaconda-auth=0.8.6=py313h06a4308_0
  - anaconda-cli-base=0.5.2=py313h06a4308_0
  - annotated-types=0.6.0=py313h06a4308_0
  - archspec=0.2.3=pyhd3eb1b0_0
  - asttokens=3.0.1=pyhd8ed1ab_0
  - boltons=25.0.0=py313h06a4308_0
  - brotlicffi=1.0.9.2=py313h6a678d5_1
  - bzip2=1.0.8=h5eee18b_6
  - c-ares=1.34.5=hef5626c_0
  - ca-certificates=2025.11.12=hbd8a1cb_0
  - certifi=2025.11.12=pyhd8ed1ab_0
  - cffi=1.17.1=py313h1fdaa30_1
  - charset-normalizer=3.3.2=pyhd3eb1b0_0
  - click=8.2.1=py313h06a4308_0
  - colorama=0.4.6=py313h06a4308_0
  - comm=0.2.3=pyhe01879c_0
  - conda=25.11.0=py313h78bf25f_0
  - conda-anaconda-telemetry=0.3.0=pyhd3eb1b0_1
  - conda-anaconda-tos=0.2.2=py313h06a4308_1
  - conda-content-trust=0.2.0=py313h06a4308_1
  - conda-libmamba-solver=25.4.0=pyhd3eb1b0_0
  - conda-package-handling=2.4.0=py313h06a4308_0
  - conda-package-streaming=0.12.0=py313h06a4308_0
  - cpp-expected=1.1.0=hdb19cb5_0
  - cryptography=45.0.5=py313hea9ce0a_0
  - dbus=1.16.2=h5bd4931_0
  - debugpy=1.8.16=py313hbdd6827_1
  - decorator=5.2.1=pyhd8ed1ab_0
  - distro=1.9.0=py313h06a4308_0
  - executing=2.2.1=pyhd8ed1ab_0
  - expat=2.7.1=h6a678d5_0
  - fmt=9.1.0=hdb19cb5_1
  - frozendict=2.4.2=py313h06a4308_0
  - icu=73.1=h6a678d5_0
  - idna=3.7=py313h06a4308_0
  - ipykernel=7.1.0=pyha191276_0
  - ipython=9.8.0=pyh53cf698_0
  - ipython_pygments_lexers=1.1.1=pyhd8ed1ab_0
  - jaraco.classes=3.4.0=py313h06a4308_0
  - jaraco.context=6.0.0=py313h06a4308_0
  - jaraco.functools=4.1.0=py313h06a4308_0
  - jedi=0.19.2=pyhd8ed1ab_1
  - jeepney=0.7.1=pyhd3eb1b0_0
  - jsonpatch=1.33=py313h06a4308_1
  - jsonpointer=3.0.0=py313h06a4308_0
  - jupyter_client=8.7.0=pyhcf101f3_0
  - jupyter_core=5.9.1=pyhc90fa1f_0
  - keyring=25.6.0=py313h06a4308_0
  - ld_impl_linux-64=2.40=h12ee557_0
  - libarchive=3.7.7=hfab0078_0
  - libcurl=8.14.1=hc1efc7f_1
  - libev=4.33=h7f8727e_1
  - libffi=3.4.4=h6a678d5_1
  - libgcc-ng=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libmamba=2.0.5=haf1ee3a_1
  - libmambapy=2.0.5=py313hdb19cb5_1
  - libmpdec=4.0.0=h5eee18b_0
  - libnghttp2=1.57.0=h2d74bed_0
  - libsodium=1.0.20=heac8642_0
  - libsolv=0.7.30=he621ea3_1
  - libssh2=1.11.1=h251f7ec_0
  - libstdcxx-ng=11.2.0=h1234567_1
  - libuuid=1.41.5=h5eee18b_0
  - libxcb=1.17.0=h9b100fa_0
  - libxml2=2.13.8=hfdd30dd_0
  - lz4-c=1.9.4=h6a678d5_1
  - markdown-it-py=2.2.0=py313h06a4308_1
  - matplotlib-inline=0.2.1=pyhd8ed1ab_0
  - mdurl=0.1.0=py313h06a4308_0
  - menuinst=2.3.1=py313h06a4308_0
  - more-itertools=10.3.0=py313h06a4308_0
  - ncurses=6.5=h7934f7d_0
  - nest-asyncio=1.6.0=pyhd8ed1ab_1
  - nlohmann_json=3.11.2=h6a678d5_0
  - openssl=3.0.17=h5eee18b_0
  - packaging=25.0=py313h06a4308_0
  - parso=0.8.5=pyhcf101f3_0
  - pcre2=10.42=hebb0a14_1
  - pexpect=4.9.0=pyhd8ed1ab_1
  - pip=25.1=pyhc872135_2
  - pkce=1.0.3=py313h06a4308_0
  - platformdirs=4.3.7=py313h06a4308_0
  - pluggy=1.5.0=py313h06a4308_0
  - prompt-toolkit=3.0.52=pyha770c72_0
  - pthread-stubs=0.3=h0ce48e5_1
  - ptyprocess=0.7.0=pyhd8ed1ab_1
  - pure_eval=0.2.3=pyhd8ed1ab_1
  - pybind11-abi=5=hd3eb1b0_0
  - pycosat=0.6.6=py313h5eee18b_2
  - pycparser=2.21=pyhd3eb1b0_0
  - pydantic=2.11.7=py313h06a4308_0
  - pydantic-core=2.33.2=py313hc6f7160_0
  - pydantic-settings=2.6.1=py313h06a4308_0
  - pygments=2.19.1=py313h06a4308_0
  - pyjwt=2.10.1=py313h06a4308_0
  - pysocks=1.7.1=py313h06a4308_0
  - python=3.13.5=h4612cfd_100_cp313
  - python-dateutil=2.9.0.post0=pyhe01879c_2
  - python-dotenv=1.1.0=py313h06a4308_0
  - python_abi=3.13=0_cp313
  - pyzmq=27.1.0=py313hcf8288c_1
  - readchar=4.0.5=py313h06a4308_0
  - readline=8.3=hc2a1206_0
  - reproc=14.2.4=h6a678d5_2
  - reproc-cpp=14.2.4=h6a678d5_2
  - requests=2.32.4=py313h06a4308_0
  - rich=13.9.4=py313h06a4308_0
  - ruamel.yaml=0.18.10=py313h5eee18b_0
  - ruamel.yaml.clib=0.2.12=py313h5eee18b_0
  - secretstorage=3.3.1=py313h06a4308_1
  - semver=3.0.2=py313h06a4308_1
  - setuptools=78.1.1=py313h06a4308_0
  - shellingham=1.5.0=py313h06a4308_0
  - simdjson=3.10.1=hdb19cb5_0
  - six=1.17.0=pyhe01879c_1
  - spdlog=1.11.0=hdb19cb5_0
  - sqlite=3.50.2=hb25bd0a_1
  - stack_data=0.6.3=pyhd8ed1ab_1
  - tk=8.6.15=h54e0aa7_0
  - tomli=2.2.1=py313h06a4308_0
  - tornado=6.5.1=py313h5eee18b_0
  - tqdm=4.67.1=py313h7040dfc_0
  - traitlets=5.14.3=pyhd8ed1ab_1
  - truststore=0.10.1=py313h06a4308_0
  - typer=0.9.0=py313h06a4308_0
  - typing-extensions=4.12.2=py313h06a4308_0
  - typing-inspection=0.4.0=py313h06a4308_0
  - typing_extensions=4.12.2=py313h06a4308_0
  - tzdata=2025b=h04d1e81_0
  - urllib3=2.5.0=py313h06a4308_0
  - wcwidth=0.2.14=pyhd8ed1ab_0
  - wheel=0.45.1=py313h06a4308_0
  - xorg-libx11=1.8.12=h9b100fa_1
  - xorg-libxau=1.0.12=h9b100fa_0
  - xorg-libxdmcp=1.1.5=h9b100fa_0
  - xorg-xorgproto=2024.1=h5eee18b_1
  - xz=5.6.4=h5eee18b_1
  - yaml-cpp=0.8.0=h6a678d5_1
  - zeromq=4.3.5=hb0a5e54_1
  - zlib=1.2.13=h5eee18b_1
  - zstandard=0.23.0=py313h2c38b39_1
  - zstd=1.5.6=hc292b87_0
  - pip:
      - anyio==4.12.1
      - cuda-bindings==12.9.4
      - cuda-pathfinder==1.3.3
      - filelock==3.20.3
      - fsspec==2026.1.0
      - h11==0.16.0
      - hf-xet==1.2.0
      - httpcore==1.0.9
      - httpx==0.28.1
      - huggingface-hub==0.36.2
      - imageio==2.37.2
      - jinja2==3.1.6
      - joblib==1.5.3
      - lazy-loader==0.4
      - lz4==4.4.5
      - markupsafe==3.0.3
      - mpmath==1.3.0
      - networkx==3.6.1
      - numpy==2.2.6
      - nvidia-cublas-cu12==12.8.4.1
      - nvidia-cuda-cupti-cu12==12.8.90
      - nvidia-cuda-nvrtc-cu12==12.8.93
      - nvidia-cuda-runtime-cu12==12.8.90
      - nvidia-cudnn-cu12==9.10.2.21
      - nvidia-cufft-cu12==11.3.3.83
      - nvidia-cufile-cu12==1.13.1.3
      - nvidia-curand-cu12==10.3.9.90
      - nvidia-cusolver-cu12==11.7.3.90
      - nvidia-cusparse-cu12==12.5.8.93
      - nvidia-cusparselt-cu12==0.7.1
      - nvidia-ml-py==13.580.82
      - nvidia-nccl-cu12==2.27.5
      - nvidia-nvjitlink-cu12==12.8.93
      - nvidia-nvshmem-cu12==3.4.5
      - nvidia-nvtx-cu12==12.8.90
      - nvitop==1.5.3
      - opencv-python==4.12.0.88
      - pandas==3.0.0
      - pillow==12.1.0
      - psutil==7.1.0
      - pyyaml==6.0.3
      - regex==2026.1.15
      - safetensors==0.7.0
      - scikit-image==0.26.0
      - scikit-learn==1.8.0
      - scipy==1.17.0
      - sympy==1.14.0
      - threadpoolctl==3.6.0
      - tifffile==2026.1.28
      - tokenizers==0.20.3
      - torch==2.10.0
      - torchvision==0.25.0
      - transformers==4.46.2
      - triton==3.6.0
      - typer-slim==0.21.1
      - typing==3.7.4.3
      - zmq==0.0.0
prefix: /scratch/taehongxi/miniconda3
